language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules

env:
  global:
    # $GITHUB_TOKEN
    secure: 'buMHpBtqq0CVAY0wYY+a9bksPucRvW9pZEdfBSKxJZ03gm2BPE0Ja6MMeoNz6VOS3Tvd5b+QXETJ8Skvngh0uVm4IDxuoCEo0qEcEBBhSZDrvlikBWEWtOttOG1NNJD5+9dYhjsogmCfmZl5McRYE46qqb5q6E1weuTQjzeoOZ05MeuRS7Ly039/Wa/0CnqhIDcXC9LJA7gQtSTDAyN5ZvjUZiH+6zBCs6Usqx2VoNReWo+70L/CaxAqKRoXzB2ESPuusr7DJl/xI9+2t4eftRPG+4cYqJ+VjPM4zSLlEBTcc9SKB8rR2/kLcIb95Dh9IkLuiiDI8JIbsh3AwcGpRR/fXkOLKw6obqWg+ll7vBNayObC4rO/F+tNbQjifyLCJneQGqw4Vt+OQhxs2Bqw0SW19XnwQVGpKDqoxOfkLJ/uLtXxZLEhT8WyY9yhZ9ODz1tqpdvIWSu1eTyUgaiSYhQ3bFeI9tJB3rplSQ8KRROOmT8jGssw3ti38ZO0/HA/51R+bkU7lN4JE4AhTq4E/l8hJCUN6baIqROOty1JYD0AR+h/xn6K5hz3hdxmb77gf6AnUFR2PbPOwasm7xKkFyQOnjHG5Plrl6NoUloaCbEBg2vMQleAEyeWOd+ISOVZqWrfo4QC5jMFo5IB1tyWJKSYkGhAe4aKQk1p82VeOpo='

install:
  - yarn install

script:
  # build successive CSS framework demo. Order matters!!! Because of cleaning
  - yarn run root-build --output-public-path https://al-un.github.io/css/
  - yarn run bootstrap4-build --output-public-path https://al-un.github.io/css/bootstrap4
  - yarn run bulma-build --output-public-path https://al-un.github.io/css/bulma
  # Ensure builds are properly done
  - ls dist/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  verbose: true
  # build on master only
  on:
    branch: master
  # default values
  target-branch: gh-pages

notifications:
  email: false
  slack:
    rooms:
      - secure: 'KGyGvZhLCiGTp9m6hTNrQxY3ygiLXiE9X1u/ThIMqwZlLd/4/30ZrTqj0rsyM8YBZIBZ0vN/M7SNv9a7z/nYWUNBEDueHoU0W+B9FNNU1epLHDbDhrOgSO1+apGptd17MTP+9RZ9jYomKwmg8VSlztpsfDyBKw9i1njKI4h6JyB3CKWTa+CvIoGMlgq7iuvLBgfBXDawwB6vS1mdfRds3dEZGJ/lwywfXf16NnH2DAo/F/eViDzdkJj8Y2Vem+imFbN5Q/Uh2zsCpsCWCIP74i8TFtcHF4r6WL/KYgbpVYA0BMMiEJfPBRxqMuVBwQfEoOHG/u96gj6V2H/CbP0MS+mmS2Jo4py9ULyx2w9oeFVn/apLe3mISfdfpTPkOEkj/F4a2nLBUhz6kF1PuObZT5+KyNqXpsXiZ3yT2gOHq9fk1Mh5eTnwVXghyb5chzA1fNLEjE46X4FUPImwAbG7MlBzfR5aSH3kGzQy7VvRsjOVd6ZzYSaaHe3eHoKtlm+BMfly5NTYmaBdbvyPH6rIpLJnkQ+EzsrzTuWinIk0uVoTIJ/CV77ZYQH7hpLtrQ8Jyx3BI2xC4kTuZ/RWy+b9l0BQrWkgwsdHALbZSAgBwll34nJfhuhaMQlCeXRNkbrECUqBnEYoxPs24azfPJN/HEh4TizQV/B2ehzGladoDyk='
    on_success: always
    on_failure: always